### ISSUE TITLE
Migrate kotlin-logging from MicroUtils.org to oshai

### ISSUE THREAD

**Issue by Michal-Kucera** [Numichi/reactive-logger#14]
As per https://github.com/oshai/kotlin-logging/issues/266, the Kotlin-logging library moved packages from microutils to oshai. Is there any plan to apply this migration in reactive-logger library too?

I tried to do so but there are plenty of breaking changes between the version we currently use here (3.x) and the latest kotlin-logging version (6.x). Unfortunately, I have no time to fix it in the end, otherwise I'd raise a PR.

Cheers!
Michal

**Comment by Numichi** [comment]
Thanks,
I will check it out soon.

**Comment by Numichi** [comment]
This will take a while. The API has completely changed.

**Comment by Numichi** [comment]
Thank you very much for bringing my attention to this Kotlin logger version. I managed to rework it. There is a new limitation that was previously supported. The Kotlin logger no longer supports transitioning from Logger to KLogger, but the KLogger (specifically a given instance) carries its Slf4j Logger, so it can be extracted. It's just that there is no API for the Kotlin Logger in the reverse direction.

There are still refinements and tests, but this part is done.

**Comment by Michal-Kucera** [comment]
Fantastic work, @Numichi! Appreciate you handling this on such short notice!
